@startuml HealthChecker_Activity

title Health Checker - Запуск сервиса 

skinparam activity {
    BackgroundColor #LightBlue
    BorderColor #333
    ArrowColor #333
}

start
:Загрузка конфигурации из .yaml;

:Каждые n секунд проверка всех\nзарегестрированных сервисов;

:Инициировать проверку\nкаждого сервиса;

fork
    :Проверить Service-1;
    :Обращение по пути\nиз конфигурации<
    fork
        :Ответ получен>
        if (Ответ {status: up}) then (Да)
            :Установить {status: up};
        else (НЕТ)
            :Установить {status: down};
        endif
    fork again
        :Таймайут из конфиигурации\nвышел>
        :Отмена запроса;
        :Установить {status: down};

    end fork
        :Вернуть ответ в HealthChecker; 
fork again
   :Проверить Service-2;
    :Обращение по пути\nиз конфигурации<
    fork
        :Ответ получен>
        if (Ответ {status: up}) then (Да)
            :Установить {status: up};
        else (НЕТ)
            :Установить {status: down};
        endif
    fork again
        :Таймайут из конфиигурации\nвышел>
        :Отмена запроса;
        :Установить {status: down};

    end fork
        :Вернуть ответ в HealthChecker; 
fork again
    :Дополнительные проверки;
end fork

:Отобразить результаты\nпроверок всех сервисов;
:Логировать результаты;


stop

@enduml
