@startuml Monitoring_UseCase
title Monitoring System - Use Case Diagram

skinparam actorBorderColor #333
skinparam usecaseBorderColor #333
skinparam usecase {
    BackgroundColor #LightBlue
    BorderColor #333
    ArrowColor #333
}

actor "Администратор" as Admin


usecase "Настройка конфигурации" as UC1
usecase "Настройка URLs" as UC2
usecase "Настройка пути\n для проверки" as UC3
usecase "Настройка времени ожидания\n ответа от сервер" as UC4
usecase "Настройка количества\n паралельных проверок" as UC5


rectangle "Health Checker System" {
    usecase "Запуск сервиса" as HC1
    usecase "Просмотр состояния сервисов" as HC2

}

' rectangle "Tracer System" {
'     usecase "Запуск сервиса" as T1
'     usecase "Просмотр трейсов" as T2

' }


Admin --> UC1 
Admin --> HC1
Admin --> HC2
' Admin --> T1
' Admin --> T2


UC1 ..> UC2: <includes> 
UC1 <.. UC3: <extends>
UC1 <.. UC4: <extends>
UC1 <.. UC5: <extends>

@enduml
